# Generated by Django 4.2.4 on 2024-04-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate_from_user', models.FloatField(blank=True, default=0, null=True)),
                ('description', models.TextField()),
                ('product_image', models.URLField()),
                ('is_discount', models.BooleanField()),
                ('discount', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
